name: main
on:
  push:
    branches:
    - main
  pull_request:
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
      with:
        set-safe-directory: true
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
  build:
    name: build
    runs-on: ubuntu-latest
    container: golang:1.24.5-alpine3.22
    strategy:
      matrix:
        include:
          - os: darwin
            arch: arm64
            suffix: ''
          - os: linux
            arch: amd64
            suffix: ''
          - os: windows
            arch: amd64
            suffix: .exe
    steps:
      - name: Install git
        run: apk add --update --no-cache git
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          set-safe-directory: true
      - name: Build
        run: |
          GOFLAGS=-buildvcs=false GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o . ./...
        shell: sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
